In [ ]:
#libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#import csv file

from google.colab import files
files.upload()

Saving ds_salaries.csv to ds_salaries.csv

{'ds_salaries.csv': b',work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size\n0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L\n1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S\n2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M\n3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S\n4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L\n5,2020,EN,FT,Data Analyst,72000,USD,72000,US,100,US,L\n6,2020,SE,FT,Lead Data Scientist,190000,USD,190000,US,100,US,S\n7,2020,MI,FT,Data Scientist,11000000,HUF,35735,HU,50,HU,L\n8,2020,MI,FT,Business Data Analyst,135000,USD,135000,US,100,US,L\n9,2020,SE,FT,Lead Data Engineer,125000,USD,125000,NZ,50,NZ,S\n10,2020,EN,FT,Data Scientist,45000,EUR,51321,FR,0,FR,S\n11,2020,MI,FT,Data Scientist,3000000,INR,40481,IN,0,IN,L\n12,2020,EN,FT,Data Scientist,35000,EUR,39916,FR,0,FR,M\n13,2020,MI,FT,Lead Data Analyst,87000,USD,87000,US,100,US,L\n14,2020,MI,FT,Data Analyst,85000,USD,85000,US,100,US,L\n15,2020,MI,FT,Data Analyst,8000,USD,8000,PK,50,PK,L\n16,2020,EN,FT,Data Engineer,4450000,JPY,41689,JP,100,JP,S\n17,2020,SE,FT,Big Data Engineer,100000,EUR,114047,PL,100,GB,S\n18,2020,EN,FT,Data Science Consultant,423000,INR,5707,IN,50,IN,M\n19,2020,MI,FT,Lead Data Engineer,56000,USD,56000,PT,100,US,M\n20,2020,MI,FT,Machine Learning Engineer,299000,CNY,43331,CN,0,CN,M\n21,2020,MI,FT,Product Data Analyst,450000,INR,6072,IN,100,IN,L\n22,2020,SE,FT,Data Engineer,42000,EUR,47899,GR,50,GR,L\n23,2020,MI,FT,BI Data Analyst,98000,USD,98000,US,0,US,M\n24,2020,MI,FT,Lead Data Scientist,115000,USD,115000,AE,0,AE,L\n25,2020,EX,FT,Director of Data Science,325000,USD,325000,US,100,US,L\n26,2020,EN,FT,Research Scientist,42000,USD,42000,NL,50,NL,L\n27,2020,SE,FT,Data Engineer,720000,MXN,33511,MX,0,MX,S\n28,2020,EN,CT,Business Data Analyst,100000,USD,100000,US,100,US,L\n29,2020,SE,FT,Machine Learning Manager,157000,CAD,117104,CA,50,CA,L\n30,2020,MI,FT,Data Engineering Manager,51999,EUR,59303,DE,100,DE,S\n31,2020,EN,FT,Big Data Engineer,70000,USD,70000,US,100,US,L\n32,2020,SE,FT,Data Scientist,60000,EUR,68428,GR,100,US,L\n33,2020,MI,FT,Research Scientist,450000,USD,450000,US,0,US,M\n34,2020,MI,FT,Data Analyst,41000,EUR,46759,FR,50,FR,L\n35,2020,MI,FT,Data Engineer,65000,EUR,74130,AT,50,AT,L\n36,2020,MI,FT,Data Science Consultant,103000,USD,103000,US,100,US,L\n37,2020,EN,FT,Machine Learning Engineer,250000,USD,250000,US,50,US,L\n38,2020,EN,FT,Data Analyst,10000,USD,10000,NG,100,NG,S\n39,2020,EN,FT,Machine Learning Engineer,138000,USD,138000,US,100,US,S\n40,2020,MI,FT,Data Scientist,45760,USD,45760,PH,100,US,S\n41,2020,EX,FT,Data Engineering Manager,70000,EUR,79833,ES,50,ES,L\n42,2020,MI,FT,Machine Learning Infrastructure Engineer,44000,EUR,50180,PT,0,PT,M\n43,2020,MI,FT,Data Engineer,106000,USD,106000,US,100,US,L\n44,2020,MI,FT,Data Engineer,88000,GBP,112872,GB,50,GB,L\n45,2020,EN,PT,ML Engineer,14000,EUR,15966,DE,100,DE,S\n46,2020,MI,FT,Data Scientist,60000,GBP,76958,GB,100,GB,S\n47,2020,SE,FT,Data Engineer,188000,USD,188000,US,100,US,L\n48,2020,MI,FT,Data Scientist,105000,USD,105000,US,100,US,L\n49,2020,MI,FT,Data Engineer,61500,EUR,70139,FR,50,FR,L\n50,2020,EN,FT,Data Analyst,450000,INR,6072,IN,0,IN,S\n51,2020,EN,FT,Data Analyst,91000,USD,91000,US,100,US,L\n52,2020,EN,FT,AI Scientist,300000,DKK,45896,DK,50,DK,S\n53,2020,EN,FT,Data Engineer,48000,EUR,54742,PK,100,DE,L\n54,2020,SE,FL,Computer Vision Engineer,60000,USD,60000,RU,100,US,S\n55,2020,SE,FT,Principal Data Scientist,130000,EUR,148261,DE,100,DE,M\n56,2020,MI,FT,Data Scientist,34000,EUR,38776,ES,100,ES,M\n57,2020,MI,FT,Data Scientist,118000,USD,118000,US,100,US,M\n58,2020,SE,FT,Data Scientist,120000,USD,120000,US,50,US,L\n59,2020,MI,FT,Data Scientist,138350,USD,138350,US,100,US,M\n60,2020,MI,FT,Data Engineer,110000,USD,110000,US,100,US,L\n61,2020,MI,FT,Data Engineer,130800,USD,130800,ES,100,US,M\n62,2020,EN,PT,Data Scientist,19000,EUR,21669,IT,50,IT,S\n63,2020,SE,FT,Data Scientist,412000,USD,412000,US,100,US,L\n64,2020,SE,FT,Machine Learning Engineer,40000,EUR,45618,HR,100,HR,S\n65,2020,EN,FT,Data Scientist,55000,EUR,62726,DE,50,DE,S\n66,2020,EN,FT,Data Scientist,43200,EUR,49268,DE,0,DE,S\n67,2020,SE,FT,Data Science Manager,190200,USD,190200,US,100,US,M\n68,2020,EN,FT,Data Scientist,105000,USD,105000,US,100,US,S\n69,2020,SE,FT,Data Scientist,80000,EUR,91237,AT,0,AT,S\n70,2020,MI,FT,Data Scientist,55000,EUR,62726,FR,50,LU,S\n71,2020,MI,FT,Data Scientist,37000,EUR,42197,FR,50,FR,S\n72,2021,EN,FT,Research Scientist,60000,GBP,82528,GB,50,GB,L\n73,2021,EX,FT,BI Data Analyst,150000,USD,150000,IN,100,US,L\n74,2021,EX,FT,Head of Data,235000,USD,235000,US,100,US,L\n75,2021,SE,FT,Data Scientist,45000,EUR,53192,FR,50,FR,L\n76,2021,MI,FT,BI Data Analyst,100000,USD,100000,US,100,US,M\n77,2021,MI,PT,3D Computer Vision Researcher,400000,INR,5409,IN,50,IN,M\n78,2021,MI,CT,ML Engineer,270000,USD,270000,US,100,US,L\n79,2021,EN,FT,Data Analyst,80000,USD,80000,US,100,US,M\n80,2021,SE,FT,Data Analytics Engineer,67000,EUR,79197,DE,100,DE,L\n81,2021,MI,FT,Data Engineer,140000,USD,140000,US,100,US,L\n82,2021,MI,FT,Applied Data Scientist,68000,CAD,54238,GB,50,CA,L\n83,2021,MI,FT,Machine Learning Engineer,40000,EUR,47282,ES,100,ES,S\n84,2021,EX,FT,Director of Data Science,130000,EUR,153667,IT,100,PL,L\n85,2021,MI,FT,Data Engineer,110000,PLN,28476,PL,100,PL,L\n86,2021,EN,FT,Data Analyst,50000,EUR,59102,FR,50,FR,M\n87,2021,MI,FT,Data Analytics Engineer,110000,USD,110000,US,100,US,L\n88,2021,SE,FT,Lead Data Analyst,170000,USD,170000,US,100,US,L\n89,2021,SE,FT,Data Analyst,80000,USD,80000,BG,100,US,S\n90,2021,SE,FT,Marketing Data Analyst,75000,EUR,88654,GR,100,DK,L\n91,2021,EN,FT,Data Science Consultant,65000,EUR,76833,DE,100,DE,S\n92,2021,MI,FT,Lead Data Analyst,1450000,INR,19609,IN,100,IN,L\n93,2021,SE,FT,Lead Data Engineer,276000,USD,276000,US,0,US,L\n94,2021,EN,FT,Data Scientist,2200000,INR,29751,IN,50,IN,L\n95,2021,MI,FT,Cloud Data Engineer,120000,SGD,89294,SG,50,SG,L\n96,2021,EN,PT,AI Scientist,12000,USD,12000,BR,100,US,S\n97,2021,MI,FT,Financial Data Analyst,450000,USD,450000,US,100,US,L\n98,2021,EN,FT,Computer Vision Software Engineer,70000,USD,70000,US,100,US,M\n99,2021,MI,FT,Computer Vision Software Engineer,81000,EUR,95746,DE,100,US,S\n100,2021,MI,FT,Data Analyst,75000,USD,75000,US,0,US,L\n101,2021,SE,FT,Data Engineer,150000,USD,150000,US,100,US,L\n102,2021,MI,FT,BI Data Analyst,11000000,HUF,36259,HU,50,US,L\n103,2021,MI,FT,Data Analyst,62000,USD,62000,US,0,US,L\n104,2021,MI,FT,Data Scientist,73000,USD,73000,US,0,US,L\n105,2021,MI,FT,Data Analyst,37456,GBP,51519,GB,50,GB,L\n106,2021,MI,FT,Research Scientist,235000,CAD,187442,CA,100,CA,L\n107,2021,SE,FT,Data Engineer,115000,USD,115000,US,100,US,S\n108,2021,SE,FT,Data Engineer,150000,USD,150000,US,100,US,M\n109,2021,EN,FT,Data Engineer,2250000,INR,30428,IN,100,IN,L\n110,2021,SE,FT,Machine Learning Engineer,80000,EUR,94564,DE,50,DE,L\n111,2021,SE,FT,Director of Data Engineering,82500,GBP,113476,GB,100,GB,M\n112,2021,SE,FT,Lead Data Engineer,75000,GBP,103160,GB,100,GB,S\n113,2021,EN,PT,AI Scientist,12000,USD,12000,PK,100,US,M\n114,2021,MI,FT,Data Engineer,38400,EUR,45391,NL,100,NL,L\n115,2021,EN,FT,Machine Learning Scientist,225000,USD,225000,US,100,US,L\n116,2021,MI,FT,Data Scientist,50000,USD,50000,NG,100,NG,L\n117,2021,MI,FT,Data Science Engineer,34000,EUR,40189,GR,100,GR,M\n118,2021,EN,FT,Data Analyst,90000,USD,90000,US,100,US,S\n119,2021,MI,FT,Data Engineer,200000,USD,200000,US,100,US,L\n120,2021,MI,FT,Big Data Engineer,60000,USD,60000,ES,50,RO,M\n121,2021,SE,FT,Principal Data Engineer,200000,USD,200000,US,100,US,M\n122,2021,EN,FT,Data Analyst,50000,USD,50000,US,100,US,M\n123,2021,EN,FT,Applied Data Scientist,80000,GBP,110037,GB,0,GB,L\n124,2021,EN,PT,Data Analyst,8760,EUR,10354,ES,50,ES,M\n125,2021,MI,FT,Principal Data Scientist,151000,USD,151000,US,100,US,L\n126,2021,SE,FT,Machine Learning Scientist,120000,USD,120000,US,50,US,S\n127,2021,MI,FT,Data Scientist,700000,INR,9466,IN,0,IN,S\n128,2021,EN,FT,Machine Learning Engineer,20000,USD,20000,IN,100,IN,S\n129,2021,SE,FT,Lead Data Scientist,3000000,INR,40570,IN,50,IN,L\n130,2021,EN,FT,Machine Learning Developer,100000,USD,100000,IQ,50,IQ,S\n131,2021,EN,FT,Data Scientist,42000,EUR,49646,FR,50,FR,M\n132,2021,MI,FT,Applied Machine Learning Scientist,38400,USD,38400,VN,100,US,M\n133,2021,SE,FT,Computer Vision Engineer,24000,USD,24000,BR,100,BR,M\n134,2021,EN,FT,Data Scientist,100000,USD,100000,US,0,US,S\n135,2021,MI,FT,Data Analyst,90000,USD,90000,US,100,US,M\n136,2021,MI,FT,ML Engineer,7000000,JPY,63711,JP,50,JP,S\n137,2021,MI,FT,ML Engineer,8500000,JPY,77364,JP,50,JP,S\n138,2021,SE,FT,Principal Data Scientist,220000,USD,220000,US,0,US,L\n139,2021,EN,FT,Data Scientist,80000,USD,80000,US,100,US,M\n140,2021,MI,FT,Data Analyst,135000,USD,135000,US,100,US,L\n141,2021,SE,FT,Data Science Manager,240000,USD,240000,US,0,US,L\n142,2021,SE,FT,Data Engineering Manager,150000,USD,150000,US,0,US,L\n143,2021,MI,FT,Data Scientist,82500,USD,82500,US,100,US,S\n144,2021,MI,FT,Data Engineer,100000,USD,100000,US,100,US,L\n145,2021,SE,FT,Machine Learning Engineer,70000,EUR,82744,BE,50,BE,M\n146,2021,MI,FT,Research Scientist,53000,EUR,62649,FR,50,FR,M\n147,2021,MI,FT,Data Engineer,90000,USD,90000,US,100,US,L\n148,2021,SE,FT,Data Engineering Manager,153000,USD,153000,US,100,US,L\n149,2021,SE,FT,Cloud Data Engineer,160000,USD,160000,BR,100,US,S\n150,2021,SE,FT,Director of Data Science,168000,USD,168000,JP,0,JP,S\n151,2021,MI,FT,Data Scientist,150000,USD,150000,US,100,US,M\n152,2021,MI,FT,Data Scientist,95000,CAD,75774,CA,100,CA,L\n153,2021,EN,FT,Data Scientist,13400,USD,13400,UA,100,UA,L\n154,2021,SE,FT,Data Science Manager,144000,USD,144000,US,100,US,L\n155,2021,SE,FT,Data Science Engineer,159500,CAD,127221,CA,50,CA,L\n156,2021,MI,FT,Data Scientist,160000,SGD,119059,SG,100,IL,M\n157,2021,MI,FT,Applied Machine Learning Scientist,423000,USD,423000,US,50,US,L\n158,2021,SE,FT,Data Analytics Manager,120000,USD,120000,US,100,US,M\n159,2021,EN,FT,Machine Learning Engineer,125000,USD,125000,US,100,US,S\n160,2021,EX,FT,Head of Data,230000,USD,230000,RU,50,RU,L\n161,2021,EX,FT,Head of Data Science,85000,USD,85000,RU,0,RU,M\n162,2021,MI,FT,Data Engineer,24000,EUR,28369,MT,50,MT,L\n163,2021,EN,FT,Data Science Consultant,54000,EUR,63831,DE,50,DE,L\n164,2021,EX,FT,Director of Data Science,110000,EUR,130026,DE,50,DE,M\n165,2021,SE,FT,Data Specialist,165000,USD,165000,US,100,US,L\n166,2021,EN,FT,Data Engineer,80000,USD,80000,US,100,US,L\n167,2021,EX,FT,Director of Data Science,250000,USD,250000,US,0,US,L\n168,2021,EN,FT,BI Data Analyst,55000,USD,55000,US,50,US,S\n169,2021,MI,FT,Data Architect,150000,USD,150000,US,100,US,L\n170,2021,MI,FT,Data Architect,170000,USD,170000,US,100,US,L\n171,2021,MI,FT,Data Engineer,60000,GBP,82528,GB,100,GB,L\n172,2021,EN,FT,Data Analyst,60000,USD,60000,US,100,US,S\n173,2021,SE,FT,Principal Data Scientist,235000,USD,235000,US,100,US,L\n174,2021,SE,FT,Research Scientist,51400,EUR,60757,PT,50,PT,L\n175,2021,SE,FT,Data Engineering Manager,174000,USD,174000,US,100,US,L\n176,2021,MI,FT,Data Scientist,58000,MXN,2859,MX,0,MX,S\n177,2021,MI,FT,Data Scientist,30400000,CLP,40038,CL,100,CL,L\n178,2021,EN,FT,Machine Learning Engineer,81000,USD,81000,US,50,US,S\n179,2021,MI,FT,Data Scientist,420000,INR,5679,IN,100,US,S\n180,2021,MI,FT,Big Data Engineer,1672000,INR,22611,IN,0,IN,L\n181,2021,MI,FT,Data Scientist,76760,EUR,90734,DE,50,DE,L\n182,2021,MI,FT,Data Engineer,22000,EUR,26005,RO,0,US,L\n183,2021,SE,FT,Finance Data Analyst,45000,GBP,61896,GB,50,GB,L\n184,2021,MI,FL,Machine Learning Scientist,12000,USD,12000,PK,50,PK,M\n185,2021,MI,FT,Data Engineer,4000,USD,4000,IR,100,IR,M\n186,2021,SE,FT,Data Analytics Engineer,50000,USD,50000,VN,100,GB,M\n187,2021,EX,FT,Data Science Consultant,59000,EUR,69741,FR,100,ES,S\n188,2021,SE,FT,Data Engineer,65000,EUR,76833,RO,50,GB,S\n189,2021,MI,FT,Machine Learning Engineer,74000,USD,74000,JP,50,JP,S\n190,2021,SE,FT,Data Science Manager,152000,USD,152000,US,100,FR,L\n191,2021,EN,FT,Machine Learning Engineer,21844,USD,21844,CO,50,CO,M\n192,2021,MI,FT,Big Data Engineer,18000,USD,18000,MD,0,MD,S\n193,2021,SE,FT,Data Science Manager,174000,USD,174000,US,100,US,L\n194,2021,SE,FT,Research Scientist,120500,CAD,96113,CA,50,CA,L\n195,2021,MI,FT,Data Scientist,147000,USD,147000,US,50,US,L\n196,2021,EN,FT,BI Data Analyst,9272,USD,9272,KE,100,KE,S\n197,2021,SE,FT,Machine Learning Engineer,1799997,INR,24342,IN,100,IN,L\n198,2021,SE,FT,Data Science Manager,4000000,INR,54094,IN,50,US,L\n199,2021,EN,FT,Data Science Consultant,90000,USD,90000,US,100,US,S\n200,2021,MI,FT,Data Scientist,52000,EUR,61467,DE,50,AT,M\n201,2021,SE,FT,Machine Learning Infrastructure Engineer,195000,USD,195000,US,100,US,M\n202,2021,MI,FT,Data Scientist,32000,EUR,37825,ES,100,ES,L\n203,2021,SE,FT,Research Scientist,50000,USD,50000,FR,100,US,S\n204,2021,MI,FT,Data Scientist,160000,USD,160000,US,100,US,L\n205,2021,MI,FT,Data Scientist,69600,BRL,12901,BR,0,BR,S\n206,2021,SE,FT,Machine Learning Engineer,200000,USD,200000,US,100,US,L\n207,2021,SE,FT,Data Engineer,165000,USD,165000,US,0,US,M\n208,2021,MI,FL,Data Engineer,20000,USD,20000,IT,0,US,L\n209,2021,SE,FT,Data Analytics Manager,120000,USD,120000,US,0,US,L\n210,2021,MI,FT,Machine Learning Engineer,21000,EUR,24823,SI,50,SI,L\n211,2021,MI,FT,Research Scientist,48000,EUR,56738,FR,50,FR,S\n212,2021,MI,FT,Data Engineer,48000,GBP,66022,HK,50,GB,S\n213,2021,EN,FT,Big Data Engineer,435000,INR,5882,IN,0,CH,L\n214,2021,EN,FT,Machine Learning Engineer,21000,EUR,24823,DE,50,DE,M\n215,2021,SE,FT,Principal Data Engineer,185000,USD,185000,US,100,US,L\n216,2021,EN,PT,Computer Vision Engineer,180000,DKK,28609,DK,50,DK,S\n217,2021,MI,FT,Data Scientist,76760,EUR,90734,DE,50,DE,L\n218,2021,MI,FT,Machine Learning Engineer,75000,EUR,88654,BE,100,BE,M\n219,2021,SE,FT,Data Analytics Manager,140000,USD,140000,US,100,US,L\n220,2021,MI,FT,Machine Learning Engineer,180000,PLN,46597,PL,100,PL,L\n221,2021,MI,FT,Data Scientist,85000,GBP,116914,GB,50,GB,L\n222,2021,MI,FT,Data Scientist,2500000,INR,33808,IN,0,IN,M\n223,2021,MI,FT,Data Scientist,40900,GBP,56256,GB,50,GB,L\n224,2021,SE,FT,Machine Learning Scientist,225000,USD,225000,US,100,CA,L\n225,2021,EX,CT,Principal Data Scientist,416000,USD,416000,US,100,US,S\n226,2021,SE,FT,Data Scientist,110000,CAD,87738,CA,100,CA,S\n227,2021,MI,FT,Data Scientist,75000,EUR,88654,DE,50,DE,L\n228,2021,SE,FT,Data Scientist,135000,USD,135000,US,0,US,L\n229,2021,SE,FT,Data Analyst,90000,CAD,71786,CA,100,CA,M\n230,2021,EN,FT,Big Data Engineer,1200000,INR,16228,IN,100,IN,L\n231,2021,SE,FT,ML Engineer,256000,USD,256000,US,100,US,S\n232,2021,SE,FT,Director of Data Engineering,200000,USD,200000,US,100,US,L\n233,2021,SE,FT,Data Analyst,200000,USD,200000,US,100,US,L\n234,2021,MI,FT,Data Architect,180000,USD,180000,US,100,US,L\n235,2021,MI,FT,Head of Data Science,110000,USD,110000,US,0,US,S\n236,2021,MI,FT,Research Scientist,80000,CAD,63810,CA,100,CA,M\n237,2021,MI,FT,Data Scientist,39600,EUR,46809,ES,100,ES,M\n238,2021,EN,FT,Data Scientist,4000,USD,4000,VN,0,VN,M\n239,2021,EN,FT,Data Engineer,1600000,INR,21637,IN,50,IN,M\n240,2021,SE,FT,Data Scientist,130000,CAD,103691,CA,100,CA,L\n241,2021,MI,FT,Data Analyst,80000,USD,80000,US,100,US,L\n242,2021,MI,FT,Data Engineer,110000,USD,110000,US,100,US,L\n243,2021,SE,FT,Data Scientist,165000,USD,165000,US,100,US,L\n244,2021,EN,FT,AI Scientist,1335000,INR,18053,IN,100,AS,S\n245,2021,MI,FT,Data Engineer,52500,GBP,72212,GB,50,GB,L\n246,2021,EN,FT,Data Scientist,31000,EUR,36643,FR,50,FR,L\n247,2021,MI,FT,Data Engineer,108000,TRY,12103,TR,0,TR,M\n248,2021,SE,FT,Data Engineer,70000,GBP,96282,GB,50,GB,L\n249,2021,SE,FT,Principal Data Analyst,170000,USD,170000,US,100,US,M\n250,2021,MI,FT,Data Scientist,115000,USD,115000,US,50,US,L\n251,2021,EN,FT,Data Scientist,90000,USD,90000,US,100,US,S\n252,2021,EX,FT,Principal Data Engineer,600000,USD,600000,US,100,US,L\n253,2021,EN,FT,Data Scientist,2100000,INR,28399,IN,100,IN,M\n254,2021,MI,FT,Data Analyst,93000,USD,93000,US,100,US,L\n255,2021,SE,FT,Big Data Architect,125000,CAD,99703,CA,50,CA,M\n256,2021,MI,FT,Data Engineer,200000,USD,200000,US,100,US,L\n257,2021,SE,FT,Principal Data Scientist,147000,EUR,173762,DE,100,DE,M\n258,2021,SE,FT,Machine Learning Engineer,185000,USD,185000,US,50,US,L\n259,2021,EX,FT,Director of Data Science,120000,EUR,141846,DE,0,DE,L\n260,2021,MI,FT,Data Scientist,130000,USD,130000,US,50,US,L\n261,2021,SE,FT,Data Analyst,54000,EUR,63831,DE,50,DE,L\n262,2021,MI,FT,Data Scientist,1250000,INR,16904,IN,100,IN,S\n263,2021,SE,FT,Machine Learning Engineer,4900000,INR,66265,IN,0,IN,L\n264,2021,MI,FT,Data Scientist,21600,EUR,25532,RS,100,DE,S\n265,2021,SE,FT,Lead Data Engineer,160000,USD,160000,PR,50,US,S\n266,2021,MI,FT,Data Engineer,93150,USD,93150,US,0,US,M\n267,2021,MI,FT,Data Engineer,111775,USD,111775,US,0,US,M\n268,2021,MI,FT,Data Engineer,250000,TRY,28016,TR,100,TR,M\n269,2021,EN,FT,Data Engineer,55000,EUR,65013,DE,50,DE,M\n270,2021,EN,FT,Data Engineer,72500,USD,72500,US,100,US,L\n271,2021,SE,FT,Computer Vision Engineer,102000,BRL,18907,BR,0,BR,M\n272,2021,EN,FT,Data Science Consultant,65000,EUR,76833,DE,0,DE,L\n273,2021,EN,FT,Machine Learning Engineer,85000,USD,85000,NL,100,DE,S\n274,2021,SE,FT,Data Scientist,65720,EUR,77684,FR,50,FR,M\n275,2021,EN,FT,Data Scientist,100000,USD,100000,US,100,US,M\n276,2021,EN,FT,Data Scientist,58000,USD,58000,US,50,US,L\n277,2021,SE,FT,AI Scientist,55000,USD,55000,ES,100,ES,L\n278,2021,SE,FT,Data Scientist,180000,TRY,20171,TR,50,TR,L\n279,2021,EN,FT,Business Data Analyst,50000,EUR,59102,LU,100,LU,L\n280,2021,MI,FT,Data Engineer,112000,USD,112000,US,100,US,L\n281,2021,EN,FT,Research Scientist,100000,USD,100000,JE,0,CN,L\n282,2021,MI,PT,Data Engineer,59000,EUR,69741,NL,100,NL,L\n283,2021,SE,CT,Staff Data Scientist,105000,USD,105000,US,100,US,M\n284,2021,MI,FT,Research Scientist,69999,USD,69999,CZ,50,CZ,L\n285,2021,SE,FT,Data Science Manager,7000000,INR,94665,IN,50,IN,L\n286,2021,SE,FT,Head of Data,87000,EUR,102839,SI,100,SI,L\n287,2021,MI,FT,Data Scientist,109000,USD,109000,US,50,US,L\n288,2021,MI,FT,Machine Learning Engineer,43200,EUR,51064,IT,50,IT,L\n289,2022,SE,FT,Data Engineer,135000,USD,135000,US,100,US,M\n290,2022,SE,FT,Data Analyst,155000,USD,155000,US,100,US,M\n291,2022,SE,FT,Data Analyst,120600,USD,120600,US,100,US,M\n292,2022,MI,FT,Data Scientist,130000,USD,130000,US,0,US,M\n293,2022,MI,FT,Data Scientist,90000,USD,90000,US,0,US,M\n294,2022,MI,FT,Data Engineer,170000,USD,170000,US,100,US,M\n295,2022,MI,FT,Data Engineer,150000,USD,150000,US,100,US,M\n296,2022,SE,FT,Data Analyst,102100,USD,102100,US,100,US,M\n297,2022,SE,FT,Data Analyst,84900,USD,84900,US,100,US,M\n298,2022,SE,FT,Data Scientist,136620,USD,136620,US,100,US,M\n299,2022,SE,FT,Data Scientist,99360,USD,99360,US,100,US,M\n300,2022,SE,FT,Data Scientist,90000,GBP,117789,GB,0,GB,M\n301,2022,SE,FT,Data Scientist,80000,GBP,104702,GB,0,GB,M\n302,2022,SE,FT,Data Scientist,146000,USD,146000,US,100,US,M\n303,2022,SE,FT,Data Scientist,123000,USD,123000,US,100,US,M\n304,2022,EN,FT,Data Engineer,40000,GBP,52351,GB,100,GB,M\n305,2022,SE,FT,Data Analyst,99000,USD,99000,US,0,US,M\n306,2022,SE,FT,Data Analyst,116000,USD,116000,US,0,US,M\n307,2022,MI,FT,Data Analyst,106260,USD,106260,US,0,US,M\n308,2022,MI,FT,Data Analyst,126500,USD,126500,US,0,US,M\n309,2022,EX,FT,Data Engineer,242000,USD,242000,US,100,US,M\n310,2022,EX,FT,Data Engineer,200000,USD,200000,US,100,US,M\n311,2022,MI,FT,Data Scientist,50000,GBP,65438,GB,0,GB,M\n312,2022,MI,FT,Data Scientist,30000,GBP,39263,GB,0,GB,M\n313,2022,MI,FT,Data Engineer,60000,GBP,78526,GB,0,GB,M\n314,2022,MI,FT,Data Engineer,40000,GBP,52351,GB,0,GB,M\n315,2022,SE,FT,Data Scientist,165220,USD,165220,US,100,US,M\n316,2022,EN,FT,Data Engineer,35000,GBP,45807,GB,100,GB,M\n317,2022,SE,FT,Data Scientist,120160,USD,120160,US,100,US,M\n318,2022,SE,FT,Data Analyst,90320,USD,90320,US,100,US,M\n319,2022,SE,FT,D

In [ ]:
#rename the unnamed column as 'id;
df = pd.read_csv("ds_salaries.csv")
df.head()
new_names=['id', 'work_year', 'experience_level', 'employment_type',
       'job_title', 'salary', 'salary_currency', 'salary_in_usd',
       'employee_residence', 'remote_ratio', 'company_location',
       'company_size']
df.columns= new_names
df.head()

,id,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [ ]:
#check if columns types are ok!
df.dtypes

id                     int64
work_year              int64
experience_level      object
employment_type       object
job_title             object
salary                 int64
salary_currency       object
salary_in_usd          int64
employee_residence    object
remote_ratio           int64
company_location      object
company_size          object
dtype: object

In [ ]:
# Salary by role

df.groupby("job_title")["salary_in_usd"].mean().round().sort_values(ascending=False)

job_title
Data Analytics Lead                         405000.0
Principal Data Engineer                     328333.0
Financial Data Analyst                      275000.0
Principal Data Scientist                    215242.0
Director of Data Science                    195074.0
Data Architect                              177874.0
Applied Data Scientist                      175655.0
Analytics Engineer                          175000.0
Data Specialist                             165000.0
Head of Data                                160163.0
Machine Learning Scientist                  158412.0
Data Science Manager                        158328.0
Director of Data Engineering                156738.0
Head of Data Science                        146719.0
Applied Machine Learning Scientist          142069.0
Lead Data Engineer                          139724.0
Data Analytics Manager                      127134.0
Cloud Data Engineer                         124647.0
Data Engineering Manager                    123227.0
Principal Data Analyst                      122500.0
ML Engineer                                 117504.0
Machine Learning Manager                    117104.0
Lead Data Scientist                         115190.0
Data Engineer                               112725.0
Research Scientist                          109020.0
Data Scientist                              108188.0
Computer Vision Software Engineer           105249.0
Staff Data Scientist                        105000.0
Machine Learning Engineer                   104880.0
Machine Learning Infrastructure Engineer    101145.0
Big Data Architect                           99703.0
Data Analyst                                 92893.0
Lead Data Analyst                            92203.0
Marketing Data Analyst                       88654.0
Lead Machine Learning Engineer               87932.0
Machine Learning Developer                   85861.0
Head of Machine Learning                     79039.0
Business Data Analyst                        76691.0
Data Science Engineer                        75803.0
BI Data Analyst                              74755.0
Data Science Consultant                      69421.0
AI Scientist                                 66136.0
Data Analytics Engineer                      64799.0
Finance Data Analyst                         61896.0
ETL Developer                                54957.0
Big Data Engineer                            51974.0
Computer Vision Engineer                     44419.0
NLP Engineer                                 37236.0
Product Data Analyst                         13036.0
3D Computer Vision Researcher                 5409.0
Name: salary_in_usd, dtype: float64

In [ ]:
#Salary By experience
df.groupby("experience_level")["salary_in_usd"].mean().round().sort_values(ascending=False)

experience_level
EX    199392.0
SE    138617.0
MI     87996.0
EN     61643.0
Name: salary_in_usd, dtype: float64

In [ ]:
#Salary by country
df.groupby("company_location")["salary_in_usd"].mean().round().sort_values(ascending=False)

company_location
RU    157500.0
US    144055.0
NZ    125000.0
IL    119059.0
JP    114127.0
AU    108043.0
DZ    100000.0
AE    100000.0
IQ    100000.0
CA     99824.0
SG     89294.0
BE     85699.0
DE     81887.0
GB     81583.0
AT     72921.0
CN     71666.0
IE     71444.0
PL     66082.0
CH     64114.0
FR     63971.0
SI     63831.0
RO     60000.0
NL     54946.0
DK     54386.0
ES     53060.0
GR     52293.0
CZ     50937.0
PT     47794.0
HR     45618.0
LU     43943.0
CL     40038.0
MY     40000.0
IT     36366.0
HU     35735.0
EE     32974.0
MX     32123.0
NG     30000.0
IN     28582.0
MT     28369.0
CO     21844.0
TR     20097.0
HN     20000.0
BR     18603.0
AS     18053.0
MD     18000.0
UA     13400.0
PK     13333.0
KE      9272.0
IR      4000.0
VN      4000.0
Name: salary_in_usd, dtype: float64

In [ ]:
df.to_csv('datos.csv', index=False)